#### Write code that does the following:

##### Create a 4x4 array using np.arange starting from 1 (so it contains values 1 through 16)
##### Print its shape, dtype, size, and total memory in bytes
##### Extract the third column as a 1D array
##### Extract the bottom-right 2x2 sub-matrix
##### Add 100 to every element in just the second row, without modifying the rest

In [1]:
import numpy as np

In [ ]:
a = np.array(np.arange(1,17).reshape(4, 4))
print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(f"Memory is {a.size * a.itemsize} Bytes")
_3col = a[:,2]
print(_3col)
print(a[2:4, 2:4])
_2Col = a[:,1]
print(_2Col + 100)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
int64
16
Memory is 128 Bytes
[ 3  7 11 15]
[[11 12]
 [15 16]]
[102 106 110 114]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [2]:
import numpy as np

def sMax(x):
    e = np.exp(x)
    return e / e.sum()

# Small Values
sml = np.array([1.0, 2.0, 3.0])
print(sMax(sml))

lrg = np.array([10.0, 20.0, 30.0])
print(sMax(lrg))

[0.09003057 0.24472847 0.66524096]
[2.06106005e-09 4.53978686e-05 9.99954600e-01]
