#### Write code that does the following:

##### Create a 4x4 array using np.arange starting from 1 (so it contains values 1 through 16)
##### Print its shape, dtype, size, and total memory in bytes
##### Extract the third column as a 1D array
##### Extract the bottom-right 2x2 sub-matrix
##### Add 100 to every element in just the second row, without modifying the rest

In [1]:
import numpy as np

In [ ]:
a = np.array(np.arange(1,17).reshape(4, 4))
print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(f"Memory is {a.size * a.itemsize} Bytes")
_3col = a[:,2]
print(_3col)
print(a[2:4, 2:4])
_2Col = a[:,1]
print(_2Col + 100)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
int64
16
Memory is 128 Bytes
[ 3  7 11 15]
[[11 12]
 [15 16]]
[102 106 110 114]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### Softmax Scaling

In [2]:
import numpy as np

def sMax(x):
    e = np.exp(x)
    return e / e.sum()

# Small Values
sml = np.array([1.0, 2.0, 3.0])
print(sMax(sml))

lrg = np.array([10.0, 20.0, 30.0])
print(sMax(lrg))

[0.09003057 0.24472847 0.66524096]
[2.06106005e-09 4.53978686e-05 9.99954600e-01]


#### L1 Norm - Manhattan Distance

In [2]:
v = np.array([3,-4])
l1_nrm = np.sum(np.abs(v))
print(l1_nrm)

7


#### Norm 2 — The L2 Norm (Euclidean Distance)


In [3]:
v = np.array([3, -4])
l2_norm = np.linalg.norm(v)
print(l2_norm)  # 5.0

5.0


#### Norm 3 — The L∞ Norm (Maximum Norm)

In [4]:
v = np.array([3, -4])
linf_norm = np.max(np.abs(v))
print(linf_norm)  # 4

4


In [5]:
import numpy as np

v = np.array([3, -4])

l1 = np.sum(np.abs(v))           # 7
l2 = np.linalg.norm(v)           # 5
linf = np.max(np.abs(v))         # 4

print(f"L1 norm: {l1}")
print(f"L2 norm: {l2}")
print(f"L∞ norm: {linf}")

L1 norm: 7
L2 norm: 5.0
L∞ norm: 4


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 6, 3])

l2_distance = np.linalg.norm(a - b)
print(l2_distance)  # 5.0

5.0


In [7]:
a = np.array([1, 2, 3], dtype=float)
b = np.array([4, 6, 3], dtype=float)

cosine_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cosine_sim)

0.8554823885364436


In [1]:
import numpy as np

data = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0],
    [2.3, 2.7],
    [2.0, 1.6],
    [1.0, 1.1],
    [1.5, 1.6],
    [1.1, 0.9]
])

ctr = data - data.mean(axis=0)
covMat = np.cov(ctr.T)
print(covMat)
eigVal, eigvec = np.linalg.eig(covMat)
print("\nEigenvalues:", eigVal)
print("Eigenvectors:\n", eigvec)

ttl = eigVal.sum()
frac = eigVal.max() / ttl
print(f"\nTop direction captures {frac*100:.1f}% of the variation")

[[0.61655556 0.61544444]
 [0.61544444 0.71655556]]

Eigenvalues: [0.0490834  1.28402771]
Eigenvectors:
 [[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]

Top direction captures 96.3% of the variation


In [4]:
odr = np.argsort(eigVal)[::-1]
print(odr)
eigVal = eigVal[odr]
eigvec = eigvec[:, odr]
print(eigvec.shape)
print("\nFirst principal component (direction of most spread):")
print(eigvec[:, 0])
print("Its eigenvalue (how much spread along it):", eigVal[0])

[0 1]
(2, 2)

First principal component (direction of most spread):
[-0.6778734  -0.73517866]
Its eigenvalue (how much spread along it): 1.2840277121727839


In [11]:
np.random.seed(42)  # Simulate=ing the dataset that is naturally elongated in 1 dierction
nPts = 200

t = np.random.randn(nPts) * 3   # Spread along the Main Direction
ns = np.random.randn(nPts) * 0.5    # Spread small ppl to it

x = t + ns
y = t - ns

dta = np.column_stack([x,y])

# 1. Center the Data
ctr = dta - dta.mean(axis=0)

# 2. Covariance Matrix
covMat = np.cov(ctr.T)
print("Covaraince Matrix: \n", covMat)

# 3. EigenValues and EigenVectors

eigvl, eigvc = np.linalg.eig(covMat)
odr = np.argsort(eigvl)[::-1]
eigvl = eigvl[odr]
eigvc = eigvc[:, odr]
print("\nEigenvalues (sorted):", eigvl)
print("Principal directions:\n", eigvc)
print("\n")


# 4. How Much variation does each direction Capture??
toVar = eigvl.sum()
for i, val in enumerate(eigvl):
    print(f"Component {i+1} captures {val/toVar*100:.1f}% of Variation")
print('\n')

# 5. Cpature only the First Principal Component
fpc = eigvc[:, 0]
cmp = ctr @ fpc

print(f"Original Data (first 10 points) :\n", dta[:10])
print(f"Compressed to 1 Dimension (first 10 points):\n", cmp)

Covaraince Matrix: 
 [[8.30675085 7.55737048]
 [7.55737048 7.78216663]]

Eigenvalues (sorted): [15.60637951  0.48253797]
Principal directions:
 [[ 0.71926557 -0.69473523]
 [ 0.69473523  0.71926557]]


Component 1 captures 97.0% of Variation
Component 2 captures 3.0% of Variation


Original Data (first 10 points) :
 [[ 1.66903614  1.31124878]
 [-0.13440064 -0.69518517]
 [ 2.48459124  1.40153999]
 [ 5.0959906   4.04218854]
 [-1.39129481 -0.01362544]
 [-1.17132339 -0.23349835]
 [ 4.99515608  4.48012081]
 [ 2.55919716  2.04541121]
 [-1.15089931 -1.665947  ]
 [ 3.55404588 -0.29868561]]
Compressed to 1 Dimension (first 10 points):
 [  2.2833483   -0.40774204   2.93267748   6.64551871  -0.83827918
  -0.83281477   6.87723889   3.43365898  -1.81329698   2.52069275
  -1.78691955  -1.78980149   1.21000287  -7.93625262  -7.14907507
  -2.20401882  -4.13401353   1.50203066  -3.68589603  -5.81809415
   6.41757261  -0.80874858   0.46676925  -5.89166811  -2.1431638
   0.6557874   -4.70983177   1.752390