#### Exercise 1

Create a 1D array of 20 evenly-spaced values between 0 and 100 using np.linspace, then reshape it into a 4x5 matrix.
Using boolean indexing, extract all values greater than 60 from that matrix.
Replace all values less than 30 with 0, directly in the matrix in place.
Using fancy indexing, extract rows 0, 2, and 3.
Transpose the matrix and print its new shape.

In [ ]:
import numpy as np

nms = np.linspace(0,100,20)
print(nms)

rNms = nms.reshape(4,5)
print(rNms)
print(rNms.shape)

msk = (rNms > 60)
msk60 = rNms[msk]
print(msk60)

msk = (rNms <= 30)
rNms[msk] = 0
print(rNms)
print(rNms[[0,2,3]])

trNms = rNms.T
print(trNms)
print(trNms.shape)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
[[  0.           5.26315789  10.52631579  15.78947368  21.05263158]
 [ 26.31578947  31.57894737  36.84210526  42.10526316  47.36842105]
 [ 52.63157895  57.89473684  63.15789474  68.42105263  73.68421053]
 [ 78.94736842  84.21052632  89.47368421  94.73684211 100.        ]]
(4, 5)
[ 63.15789474  68.42105263  73.68421053  78.94736842  84.21052632
  89.47368421  94.73684211 100.        ]
[[  0.           0.           0.           0.           0.        ]
 [  0.          31.57894737  36.84210526  42.10526316  47.36842105]
 [ 52.63157895  57.89473684  63.15789474  68.42105263  73.68421053]
 [ 78.94736842  84.21052632  89.47368421  94.73684211 100.        ]]
[[  0.           0.           0.           0.           0.        ]
 [ 52.6