#### Boolean Mask

In [2]:
import numpy as np

rds = np.array([22.1, 85.3, 21.8, 999.0, 23.5, -200.0, 20.2, 77.4, 24.1])
msk = (rds >= 15) & (rds <= 45)
print(msk)
rds = rds[msk]
print(rds)

[ True False  True False  True False  True False  True]
[22.1 21.8 23.5 20.2 24.1]


#### Boolean Mask with Multiple Conditions

In [3]:
import numpy as np

data = np.array([5, 12, 28, 45, 67, 3, 89, 55, 19, 33])

# AND — both conditions must be true
between = data[(data >= 10) & (data <= 50)]
print(between)
# Output: [12 28 45 19 33]

# OR — at least one condition must be true
extreme = data[(data < 10) | (data > 60)]
print(extreme)
# Output: [ 5  3 89 67]

# NOT — inverts the condition
not_extreme = data[~((data < 10) | (data > 60))]
print(not_extreme)
# Output: [12 28 45 55 19 33]

[12 28 45 19 33]
[ 5 67  3 89]
[12 28 45 55 19 33]
