#### Boolean Mask

In [2]:
import numpy as np

rds = np.array([22.1, 85.3, 21.8, 999.0, 23.5, -200.0, 20.2, 77.4, 24.1])
msk = (rds >= 15) & (rds <= 45)
print(msk)
rds = rds[msk]
print(rds)

[ True False  True False  True False  True False  True]
[22.1 21.8 23.5 20.2 24.1]


#### Boolean Mask with Multiple Conditions

In [3]:
import numpy as np

data = np.array([5, 12, 28, 45, 67, 3, 89, 55, 19, 33])

# AND — both conditions must be true
between = data[(data >= 10) & (data <= 50)]
print(between)
# Output: [12 28 45 19 33]

# OR — at least one condition must be true
extreme = data[(data < 10) | (data > 60)]
print(extreme)
# Output: [ 5  3 89 67]

# NOT — inverts the condition
not_extreme = data[~((data < 10) | (data > 60))]
print(not_extreme)
# Output: [12 28 45 55 19 33]

[12 28 45 19 33]
[ 5 67  3 89]
[12 28 45 55 19 33]


#### Masked assignment


In [5]:
sDta = np.array([22.1, 85.3, 21.8, 999.0, 23.5, -200, 20.2])
sDta[sDta > 45] = np.nan
sDta[sDta < 0] = np.nan
print(sDta)

[22.1  nan 21.8  nan 23.5  nan 20.2]


#### Fancy Indexing
Boolean indexing filters by condition. Fancy indexing lets you select specific elements by their exact index positions — in any order, repeated as many times as you want, non-contiguously.
The syntax looks similar to basic slicing, but the behavior is completely different. Instead of giving NumPy a range, you give it a list of specific positions.

In [6]:
import numpy as np

prices = np.array([100, 200, 300, 400, 500, 600, 700])

# Basic slicing — a contiguous range, returns a VIEW
print(prices[1:4])
# Output: [200 300 400]

# Fancy indexing — explicit positions, always returns a COPY
print(prices[[0, 3, 6]])
# Output: [100 400 700]

# You can repeat indices — useful for duplication or sampling
print(prices[[0, 0, 2]])
# Output: [100 100 300]

# You can use it to reorder
print(prices[[6, 5, 4, 3]])
# Output: [700 600 500 400]

[200 300 400]
[100 400 700]
[100 100 300]
[700 600 500 400]


In 2D arrays, fancy indexing becomes very powerful. You can select entire rows, or you can pick specific coordinate pairs

In [8]:
mat = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(mat[[0,2]]) # Select rows 0 and 2
# Select specific (row, col) coordinate pairs
rows = [0, 1, 2]
cols = [1, 2, 3]
print(mat[rows, cols])


[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 2  7 12]
