#### Boolean Mask

In [2]:
import numpy as np

rds = np.array([22.1, 85.3, 21.8, 999.0, 23.5, -200.0, 20.2, 77.4, 24.1])
msk = (rds >= 15) & (rds <= 45)
print(msk)
rds = rds[msk]
print(rds)

[ True False  True False  True False  True False  True]
[22.1 21.8 23.5 20.2 24.1]


#### Boolean Mask with Multiple Conditions

In [3]:
import numpy as np

data = np.array([5, 12, 28, 45, 67, 3, 89, 55, 19, 33])

# AND — both conditions must be true
between = data[(data >= 10) & (data <= 50)]
print(between)
# Output: [12 28 45 19 33]

# OR — at least one condition must be true
extreme = data[(data < 10) | (data > 60)]
print(extreme)
# Output: [ 5  3 89 67]

# NOT — inverts the condition
not_extreme = data[~((data < 10) | (data > 60))]
print(not_extreme)
# Output: [12 28 45 55 19 33]

[12 28 45 19 33]
[ 5 67  3 89]
[12 28 45 55 19 33]


#### Masked assignment


In [5]:
sDta = np.array([22.1, 85.3, 21.8, 999.0, 23.5, -200, 20.2])
sDta[sDta > 45] = np.nan
sDta[sDta < 0] = np.nan
print(sDta)

[22.1  nan 21.8  nan 23.5  nan 20.2]


#### Fancy Indexing
Boolean indexing filters by condition. Fancy indexing lets you select specific elements by their exact index positions — in any order, repeated as many times as you want, non-contiguously.
The syntax looks similar to basic slicing, but the behavior is completely different. Instead of giving NumPy a range, you give it a list of specific positions.

In [6]:
import numpy as np

prices = np.array([100, 200, 300, 400, 500, 600, 700])

# Basic slicing — a contiguous range, returns a VIEW
print(prices[1:4])
# Output: [200 300 400]

# Fancy indexing — explicit positions, always returns a COPY
print(prices[[0, 3, 6]])
# Output: [100 400 700]

# You can repeat indices — useful for duplication or sampling
print(prices[[0, 0, 2]])
# Output: [100 100 300]

# You can use it to reorder
print(prices[[6, 5, 4, 3]])
# Output: [700 600 500 400]

[200 300 400]
[100 400 700]
[100 100 300]
[700 600 500 400]


In 2D arrays, fancy indexing becomes very powerful. You can select entire rows, or you can pick specific coordinate pairs

In [8]:
mat = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(mat[[0,2]]) # Select rows 0 and 2
# Select specific (row, col) coordinate pairs
rows = [0, 1, 2]
cols = [1, 2, 3]
print(mat[rows, cols])


[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 2  7 12]


#### np.where()
np.where is one of those functions you will use so often it becomes automatic. It is the array equivalent of a ternary expression: if the condition is true, use this value; otherwise use that value.

In [12]:
scrs = np.array([22,67,89,56,87,93,45,78,65,62,98,23,67,89,35,89,46,74,78])
res = np.where(scrs >= 60, 'pass', 'fail')
print(res)

flrd = np.where(scrs < 60, 60, scrs)
print(flrd)

['fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'pass'
 'pass' 'fail' 'pass' 'pass' 'fail' 'pass' 'fail' 'pass' 'pass']
[60 67 89 60 87 93 60 78 65 62 98 60 67 89 60 89 60 74 78]


#### Reshape
the shape of a NumPy array is not a property of the data. It is a property of how you choose to look at the data. The underlying memory block does not move, does not rearrange, does not get copied when you reshape. NumPy just changes the instruction it uses to interpret that block.
Think of it like a 12-page document. You can lay the pages out in a single row — that is a 1D view. You can arrange them in 3 rows of 4 pages — that is a 2D view. You can stack them in 2 layers of 2 rows and 3 columns — that is a 3D view. The content of each page did not change. The arrangement of pages in your head changed.

In [6]:
import numpy as np

# A flat 1D array of 12 elements
flat = np.arange(1, 13)
print(flat)
# Output: [ 1  2  3  4  5  6  7  8  9 10 11 12]
print(flat.shape)   # (12,)

# Reshape into 3 rows, 4 columns
as_3x4 = flat.reshape(3, 4)
print(as_3x4)
# Output:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Reshape into 4 rows, 3 columns
as_4x3 = flat.reshape(4, 3)
print(as_4x3)
# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

# Reshape into 2 layers of 2 rows and 3 columns — this is 3D
as_3d = flat.reshape(2, 2, 3)
print(as_3d)
print(as_3d.shape)   # (2, 2, 3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [5]:
import numpy as np

flt = np.arange(1,13)
print(flt)

print(flt.shape)

r3c4 = flt.reshape(3,4)
print(r3c4)
print(r3c4.shape)

l2r2c3 = flt.reshape(2,2,3)
print(l2r2c3)
print(l2r2c3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


#### The -1 Trick
When you are reshaping and you know one dimension but not the other, you can use -1 and let NumPy calculate it
You can only use -1 in one dimension, not multiple. If NumPy has two unknowns, there is no unique solution, and it raises an error.

In [8]:
flt = np.arange(24)

mc = flt.reshape(4,-1)
print(mc)
print(mc.shape)

mr = flt.reshape(-1, 4)
print(mr)
print(mr.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)


#### Flatten and Ravel

In [11]:
mat = np.arange(1,13)
mat = mat.reshape(4,3)
matCpy = mat
print(mat)
print(mat.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


#### Flatten 
ALWAYS returns a copy. Safe. Slower.

In [13]:
# Flatten
fltn = mat.flatten()
print(f"Before Changing Elements : {fltn}")
fltn[0] = 999
print(f"After Changing the Element : {fltn}")
print(fltn.shape)
if(matCpy.all() == mat.all()):
    print("Original Matrix Unchanged")
else:
    print("Original Matrix Changed")

Before Changing Elements : [ 1  2  3  4  5  6  7  8  9 10 11 12]
After Changing the Element : [999   2   3   4   5   6   7   8   9  10  11  12]
(12,)
Original Matrix Unchanged


#### Ravel 
Ravel is not always a view — it depends on memory layout
When it cannot return a view, it returns a copy
The behavior is sometimes unpredictable for non-contiguous arrays
In doubt, use flatten for safety


In [ ]:
# Ravel
rvl = mat.ravel()
print(f"Before Changing Elements : {rvl}")
rvl[1] = 999
print(f"After Changing the Elements : {rvl}")
print(rvl.shape)
print(mat)

Before Changing Elements : [  1 999   3   4   5   6   7   8   9  10  11  12]
After Changing the Elements : [  1 999   3   4   5   6   7   8   9  10  11  12]
(12,)
[[  1 999   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
[[  1 999   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


#### Transpose
Transpose flips the array along its diagonal, rows become columns and columns become rows.
Transpose is always a view. Modifying the transposed array modifies the original. Keep this in mind.


In [18]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original shape:", matrix.shape)   # (2, 3)

transposed = matrix.T
print(transposed)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]
print("Transposed shape:", transposed.shape)   # (3, 2)

Original shape: (2, 3)
[[1 4]
 [2 5]
 [3 6]]
Transposed shape: (3, 2)
