In [2]:
import numpy as np

In [5]:
print(np.zeros(5))
print(np.ones(5))


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [9]:
# Fill the array with a specific Number X, n times
n = 5
x = 7
print(np.full(n,x))

[7 7 7 7 7]


In [12]:
# Arange the array with WOkring Like the Python Range...
# Start, end(Not Including), step
print(np.arange(1,8,1))

[1 2 3 4 5 6 7]


In [18]:
# LinSpace - Give me Exactly "n" Evenly spaced points between start and end
# np.linspace(start, end, n)
print(np.linspace(0, 1000000, 10))
print(np.linspace(0, 10, 3))

[      0.          111111.11111111  222222.22222222  333333.33333333
  444444.44444444  555555.55555556  666666.66666667  777777.77777778
  888888.88888889 1000000.        ]
[ 0.  5. 10.]


In [20]:
b = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(4, 2)
2
8
int64


In [ ]:
# Reshaping :  Change the shape of an array without changing its data. The elements stay the same, they just get rearranged into a different structure.
# use -1 for one dimension and NumPy will figure it out

a = np.arange(1,13)
b = a.reshape(3,-1)
c = a.reshape(-1,6)
print(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [26]:
print(np.arange(24).reshape(4,-1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [3]:
x = np.array([2, 4, 6])
y = np.array([1, 2, 3])
res = (x - y) ** 2
print(res)

[1 4 9]


In [4]:
# Boolean Array, Vectorized Boolean Operations
a = np.array([10,20,30,40,50])
print(a > 20)
print(a == 30)
print(a <= 10)

[False False  True  True  True]
[False False  True False False]
[ True False False False False]


In [7]:
# Using the Boolean Array to Filter Data
mask = a > 20
print(a[mask])
scores = np.array([88, 45, 92, 67, 73, 55])
scores[scores > 70]

[30 40 50]


array([88, 92, 73])

#### Aggregate Functions

In [10]:
print(scores.mean())
print(scores.sum())
print(scores.min())
print(scores.max())
print(scores.std())
print(np.median(scores))

70.0
420
45
92
16.713268182295565
70.0


In [11]:
data = np.array([5, 10, 15, 20])
print(np.sum(data))
print(np.mean(data))

50
12.5


In [ ]:
# 2D Arrays with Axes
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


In [15]:
b = np.array([[10, 20],
              [30, 40],
              [50, 60]])

print(np.mean(b, axis=1))


[15. 35. 55.]


In [5]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]


In [10]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b[0,0])
print(b[1,2])
print(b[2,1])
print(b[:,0])
print(b[0,:])

1
6
8
[1 4 7]
[1 2 3]


In [28]:
# Rows Start from 0th Index, But the column Starts from Index 1, Thats the Whole Idea
c = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(c[::2, :])

[[10 20 30]
 [70 80 90]]


In [32]:
# a[1::3] -- start from index 1, go to the end, step by 3.
a = np.array([10, 20, 30, 40, 50, 60, 70])
print(a[0::2])

[10 30 50 70]
