# NumPy Fundamentals

This notebook covers the essential concepts of NumPy, a powerful library for numerical computing in Python. We'll explore array creation, manipulation, operations, and data access patterns.

In [2]:
import numpy as np

## 1. Array Creation

NumPy provides several convenient functions to create arrays. Here, we'll explore `zeros()`, `ones()`, and `full()` which generate arrays filled with specific values.

- **`np.zeros(n)`**: Creates an array of size n filled with zeros
- **`np.ones(n)`**: Creates an array of size n filled with ones
- **`np.full(n, x)`**: Creates an array of size n filled with the value x

In [2]:
print(np.zeros(5))
print(np.ones(5))


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [3]:
# Fill the array with a specific Number X, n times
n = 5
x = 7
print(np.full(n,x))

[7 7 7 7 7]


## 2. Array Generation with Ranges

NumPy offers flexible ways to generate arrays with specific patterns:

- **`np.arange(start, end, step)`**: Similar to Python's `range()`, but returns a NumPy array. Generates values from `start` to `end` (exclusive) with a given step size.
- **`np.linspace(start, end, n)`**: Creates exactly n evenly spaced points between `start` and `end` (inclusive). Useful for generating smooth ranges of values.

In [4]:
# Arange the array with WOkring Like the Python Range...
# Start, end(Not Including), step
print(np.arange(1,8,1))

[1 2 3 4 5 6 7]


In [5]:
# LinSpace - Give me Exactly "n" Evenly spaced points between start and end
# np.linspace(start, end, n)
print(np.linspace(0, 1000000, 10))
print(np.linspace(0, 10, 3))

[      0.          111111.11111111  222222.22222222  333333.33333333
  444444.44444444  555555.55555556  666666.66666667  777777.77777778
  888888.88888889 1000000.        ]
[ 0.  5. 10.]


In [6]:
b = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(4, 2)
2
8
int64


## 3. Understanding Array Properties

Every NumPy array has attributes that describe its structure and data type:

- **`.shape`**: Returns a tuple indicating the dimensions. For example, (4, 2) means 4 rows and 2 columns.
- **`.ndim`**: Number of dimensions (1D array has ndim=1, 2D array has ndim=2, etc.)
- **`.size`**: Total number of elements in the array (product of all dimensions)
- **`.dtype`**: Data type of the array elements (int64, float64, etc.)

In [7]:
# Reshaping :  Change the shape of an array without changing its data. The elements stay the same, they just get rearranged into a different structure.
# use -1 for one dimension and NumPy will figure it out

a = np.arange(1,13)
b = a.reshape(3,-1)
c = a.reshape(-1,6)
print(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## 4. Reshaping Arrays

**Reshaping** allows you to change the dimensions of an array without changing its data. The elements remain the same; they're just rearranged into a different structure.

- **`.reshape(rows, cols)`**: Reorganizes the array into a new shape (e.g., reshape a 1D array of 12 elements into 3×4 or 4×3)
- **Use `-1` for automatic dimension calculation**: If you specify `-1` for one dimension, NumPy automatically calculates that dimension based on the array size and other dimensions. This is very helpful when you know the total elements but want to let NumPy figure out one dimension.

In [8]:
print(np.arange(24).reshape(4,-1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
x = np.array([2, 4, 6])
y = np.array([1, 2, 3])
res = (x - y) ** 2
print(res)

[1 4 9]


## 5. Element-wise Operations

NumPy excels at **vectorized operations**, which apply operations to entire arrays efficiently without explicit loops. 

- Operations like `+`, `-`, `*`, `/`, `**` are applied element-by-element
- This is much faster than traditional Python loops
- Operations between arrays of the same shape combine corresponding elements
- Operations work seamlessly with Python operators, making code clean and readable

In [10]:
# Boolean Array, Vectorized Boolean Operations
a = np.array([10,20,30,40,50])
print(a > 20)
print(a == 30)
print(a <= 10)

[False False  True  True  True]
[False False  True False False]
[ True False False False False]


## 6. Boolean Arrays and Filtering

Boolean operations in NumPy compare array elements against a condition and return arrays of True/False values.

- **Comparison operators** (`>`, `<`, `==`, `!=`, `<=`, `>=`) create boolean arrays
- These boolean arrays can be used as **masks** to filter data
- Mask-based indexing `array[boolean_mask]` selects only elements where the mask is True
- This enables powerful data filtering without loops

In [11]:
# Using the Boolean Array to Filter Data
mask = a > 20
print(a[mask])
scores = np.array([88, 45, 92, 67, 73, 55])
scores[scores > 70]

[30 40 50]


array([88, 92, 73])

## 7. Aggregate Functions

Aggregate functions compute a single value from an entire array or along a specific axis.

### Common Aggregate Functions:
- **`.mean()` or `np.mean()`**: Calculates the average of array elements
- **`.sum()` or `np.sum()`**: Returns the sum of all elements
- **`.min()` or `np.min()`**: Finds the minimum value
- **`.max()` or `np.max()`**: Finds the maximum value
- **`.std()` or `np.std()`**: Computes the standard deviation (spread of values)
- **`np.median()`**: Finds the middle value

### Using the `axis` parameter:
For 2D arrays, you can specify:
- **`axis=0`**: Aggregate along rows (compute per column)
- **`axis=1`**: Aggregate along columns (compute per row)
- **No axis specified**: Aggregate across the entire array

In [12]:
print(scores.mean())
print(scores.sum())
print(scores.min())
print(scores.max())
print(scores.std())
print(np.median(scores))

70.0
420
45
92
16.713268182295565
70.0


In [13]:
data = np.array([5, 10, 15, 20])
print(np.sum(data))
print(np.mean(data))

50
12.5


In [14]:
# 2D Arrays with Axes
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


In [15]:
b = np.array([[10, 20],
              [30, 40],
              [50, 60]])

print(np.mean(b, axis=1))


[15. 35. 55.]


In [5]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]


## 8. Indexing and Slicing

Accessing specific elements or subsets of an array is fundamental to working with data.

### Slicing with Steps:
- **`array[start:end:step]`**: Slice with a step size. For example:
  - `array[0::2]` means start at index 0, go to end, with step 2 (every other element)
  - `array[1::3]` means start at index 1, go to end, with step 3
  - `array[::2, :]` means every other row, all columns

### 1D Array Indexing:
- **`array[i]`**: Access element at index i (0-indexed)
- **`array[-1]`**: Access last element (negative indexing)
- **`array[start:end]`**: Slice from start (inclusive) to end (exclusive)

In [15]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # 10  — first element
print(arr[-1])   # 50  — last element
print(arr[1:4])  # [20 30 40]  — slice, start inclusive, stop exclusive
print(arr[::2])  # [10 30 50]  — every second element

10
50
[20 30 40]
[10 30 50]


### 2D Array Indexing:
- **`array[row, col]`**: Access element at specific row and column
- **`array[:, col]`**: Get all rows of a specific column
- **`array[row, :]`**: Get all columns of a specific row
- **`array[row1:row2, col1:col2]`**: Get a rectangular subarray


In [16]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b[0,0])
print(b[1,2])
print(b[2,1])
print(b[:,0])
print(b[0,:])
print(b[0:1, 1:2])

1
6
8
[1 4 7]
[1 2 3]
[[2]]


In [17]:
# Rows Start from 0th Index, But the column Starts from Index 1, Thats the Whole Idea
c = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(c[::2, :])

[[10 20 30]
 [70 80 90]]


In [18]:
# a[1::3] -- start from index 1, go to the end, step by 3.
a = np.array([10, 20, 30, 40, 50, 60, 70])
print(a[0::2])

[10 30 50 70]


In [3]:
import time

sz = 1_000_000
pyLst = list(range(sz))
st = time.time()
res = [x * 2 for x in pyLst]
pyTm = time.time() - st

# Numpy

npArr = np.arange(sz)
st = time.time()
res = npArr * 2
npTm = time.time() - st

print(f"Python List : {pyTm:.4f} Secs")
print(f"Numpy Array Size : {npTm:.4f} Secs")
print(f"Numpy is {pyTm / npTm:.1f}x Faster..")

Python List : 0.0324 Secs
Numpy Array Size : 0.0092 Secs
Numpy is 3.5x Faster..


## Summary

You've now learned the **NumPy fundamentals**:
1. **Array Creation**: Using zeros, ones, full, arange, and linspace
2. **Array Properties**: Understanding shape, dimensions, size, and data types
3. **Reshaping**: Reorganizing arrays without losing data
4. **Vectorized Operations**: Performing fast, element-wise computations
5. **Boolean Filtering**: Creating masks and filtering data efficiently
6. **Aggregation**: Computing statistics across arrays and dimensions
7. **Indexing & Slicing**: Accessing specific elements and subarrays with powerful syntax

These concepts form the foundation for data manipulation, scientific computing, and machine learning with NumPy!