In [ ]:
import  numpy as np

sls = np.array([
    [12000,  8500, 15000, 22000,  6000],   # Q1
    [14000,  9200, 13500, 24000,  7200],   # Q2
    [11500,  8000, 16000, 20000,  8500],   # Q3
    [16000, 10500, 14500, 26000,  9000]    # Q4
])
print(sls.shape)


(4, 5)
[53500 36200 59000 92000 30700]


In [4]:
prodTl = sls.sum(axis=0)
print(prodTl)
print(prodTl.shape)

[53500 36200 59000 92000 30700]
(5,)


In [3]:
qytrTls = sls.sum(axis=1)
print(qytrTls)
print(qytrTls.shape)

[63500 67900 64000 76000]
(4,)


In [6]:
sales = np.array([
    [12000,  8500, 15000, 22000,  6000],
    [14000,  9200, 13500, 24000,  7200],
    [11500,  8000, 16000, 20000,  8500],
    [16000, 10500, 14500, 26000,  9000]
])

# Which product had the highest single-quarter sales?
print(sales.max(axis=0))

# Which quarter had the lowest single-product sales?
print(sales.min(axis=1))

# Average quarterly revenue per product
print(sales.mean(axis=0).astype(int))

# Which quarter had the highest total revenue?
best_quarter = sales.sum(axis=1).argmax()
print(f"Best quarter: Q{best_quarter + 1}")

print(sales.std(axis=0).astype(int))


[16000 10500 16000 26000  9000]
[6000 7200 8000 9000]
[13375  9050 14750 23000  7675]
Best quarter: Q4
[1780  939  901 2236 1169]


#### keepdims — Preserving Shape After Aggregation
By default, when you aggregate along an axis, that dimension disappears from the result. Sometimes you need the result to keep the original number of dimensions, but with size 1 where the collapse happened. That is what keepdims=True does.

In [14]:
dta = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(dta.shape)
row = dta.sum(axis=1)
print(row)
print(row.shape)

rkept = dta.sum(axis=1, keepdims=True)
print(rkept)
print(rkept.shape)

(3, 3)
[ 60 150 240]
(3,)
[[ 60]
 [150]
 [240]]
(3, 1)


In [ ]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Cumulative sum — each element is the running total
print(np.cumsum(arr))
# Output: [ 3  4  8  9 14 23 25 31 36 39]

# Index of the minimum and maximum values
print(np.argmin(arr))   # 1 — position of the smallest value (1)
print(np.argmax(arr))   # 5 — position of the largest value (9)

# Percentile — what value is at the 75th percentile?
print(np.percentile(arr, 75))   # 5.25

# Median
print(np.median(arr))   # 3.5

#### Broadcasting
You have a 2D array and you want to do arithmetic between it and a 1D array. Mathematically you know what you mean — maybe you want to subtract the column mean from every row, or normalize each column by its maximum. But the shapes do not match.

In [15]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# shape: (3, 3)

column_means = data.mean(axis=0)
print(column_means)   # [40. 50. 60.]
# shape: (3,)

# This works — even though shapes are different
centered = data - column_means
print(centered)
# Output:
# [[-30. -30. -30.]
#  [  0.   0.   0.]
#  [ 30.  30.  30.]]

[40. 50. 60.]
[[-30. -30. -30.]
 [  0.   0.   0.]
 [ 30.  30.  30.]]
